### ISSUE TITLE
Feature: add a "bypass" environment variable

### ISSUE THREAD

**Issue by abeforgit** [mu-semtech/mu-cache#7]
Sometimes when debugging/developing around the cache, it can be handy to disable it without messing up the dispatcher configuration. A sort of "bypass" environment variable which would cause the cache to "always miss" would be a nice-to-have.

**Comment by erikap** [comment]
@abeforgit  Isn't it an option to temporarily link `resource` as `cache` in dispatcher like
```yml
services:
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    links:
      - resource:cache   
```
